### ISSUE TITLE
JUnit Tests

### ISSUE THREAD

**Issue by ghost** [ronwalf/Poolesville-2010-Games-Project#1]
I don't think the JUnit tests work with "assertEquals" for arrays of primitives. I changed
    assertEquals(new double[]{-1.0, 1.0}, TicTacTransition.instance.score( state ));
to
    assertTrue(Arrays.equals(new double[]{-1.0, 1.0}, TicTacTransition.instance.score( state )));

and it seems to work for me.

The tests were also failing because of this on the "FinishedGame" tests:
    assertEquals(0, moves.size());

I think this is because the "enumerate" method of TicTacTransition enumerates states for all null cells, even if the current state is supposed to be the end of the game. To fix this, I added in
    if(score(s) == null)
before the for loop that checks which cells are empty.

**Comment by ronwalf** [comment]
Addition of get(i,j) to Board.  Correction to enumerate and tests.  Closed by 40ff33aa1bc6c80ba6b570cb34bdd1f43a0942f7
