### ISSUE TITLE
Posible Changes

### ISSUE THREAD

**Issue by josjjara** [ronwalf/Poolesville-2010-Games-Project#2]
Hi if you are still working on the repository I would like to offer some changes in regards of the use of SOLID principles. If its inactive or you are not interested in the input, disregard this message. If not I have attached a word documment file. Might need translation. 
Thank you.

**Comment by ronwalf** [comment]
Hi,
Thank you for looking at this old teaching project of mine. It is no longer in active development. I've deleted the .docx file, as clicking on Word documents from the web is problematic from a security perspective. If you submit a pull request, I'd be happy to review it.
